version: "3.4"

services:
    pandoc:
        image: "registry.gitlab.com/hassiweb-programming/md2pdf"
        build: docker/
        volumes: 
            - ./docs/:/data
        # entrypoint: /bin/bash        
        command: >
            pandoc test.md
            -s
            -o test.pdf
            --pdf-engine=lualatex
            -V documentclass=ltjsarticle 
            -V classoption=pandoc
            --lua-filter /opt/lualatex/filter/gitlab-math.lua
